---
title: "Baby-Names"
author: "Mia Fitzgerald"
date: "4/2/2026"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
library(knitr)
library(tidyverse)
library(babynames)
library(janitor)
```


### Mutated Proportion Into Rounded Percentages 


```{r}
data(babynames)

babynames2 <- babynames %>%
  mutate(prop_percent = round(prop * 100, 2))

babynames2 %>% 
  head(6) %>%
  kable()

```


^[Question 1 complete]


### Using Strings in a New Column 


```{r}
babynames3 <- babynames2 %>%
  mutate(percent_year = str_glue("{prop_percent}% in {year}"))

babynames3 %>% 
  head(6) %>%
  kable()

```


^[Question 2 complete]


### Filtered For Specific Name and Sex


```{r}
babynames4 <- babynames3 %>%
  filter(name == "Cora", sex == "F")

babynames4 %>%
  head(6) %>%
  kable()

```


^[Question 3 complete]


### Five Random Rows Using set.seed()


```{r}
set.seed(42)
babynames_sliced <- babynames4 %>%
  slice_sample(n = 5) %>%
  arrange(year)

babynames_sliced %>%
  kable()

```


^[Question 4 complete]


### Making a Collapsed String


```{r}
babystring <- babynames_sliced %>%
  pull(percent_year) %>%
  str_flatten(collapse = ", ", last = ", and ")

babystring %>%
  str_view()

```


^[Question 5 complete]
